import re
from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.pdfgen import canvas

from app.core.state import EDAState


PAGE_WIDTH, PAGE_HEIGHT = A4
LEFT_MARGIN = 1.8 * cm
RIGHT_MARGIN = 1.8 * cm
TOP_MARGIN = 1.8 * cm
BOTTOM_MARGIN = 1.6 * cm
CONTENT_WIDTH = PAGE_WIDTH - LEFT_MARGIN - RIGHT_MARGIN

COLOR_INK = colors.HexColor("#1f2933")
COLOR_MUTED = colors.HexColor("#64748b")
COLOR_BORDER = colors.HexColor("#d9e2ec")
COLOR_PANEL = colors.HexColor("#f8fafc")
COLOR_PANEL_ALT = colors.HexColor("#eef6ff")
COLOR_ACCENT = colors.HexColor("#2563eb")
COLOR_ACCENT_DARK = colors.HexColor("#1e3a8a")
COLOR_SUCCESS = colors.HexColor("#0f766e")
MAX_SAMPLE_ROWS = 5
MAX_SAMPLE_COLUMNS_PER_TABLE = 5


def build_pdf_report(state: EDAState) -> bytes:
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    y = PAGE_HEIGHT - TOP_MARGIN
    page_number = 1

    def sanitize(text: str) -> str:
        text = re.sub(r"\s*\(llm_error=[^)]*\)", "", text or "")
        return text.replace("_", " ")

    def humanize(value: str) -> str:
        text = sanitize(str(value)).strip().replace("-", " ")
        text = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", text)
        return text.title()

    def fmt(value: Any) -> str:
        if value is None:
            return "Not available"
        if isinstance(value, float):
            return f"{value:,.4g}"
        if isinstance(value, int):
            return f"{value:,}"
        if isinstance(value, dict):
            return ", ".join(f"{humanize(key)}: {fmt(value[key])}" for key in sorted(value))
        return sanitize(str(value))

    def fmt_percent(value: Any) -> str:
        if value is None:
            return "Not available"
        if isinstance(value, (float, int)):
            return f"{float(value):.1%}"
        return fmt(value)

    def draw_footer() -> None:
        pdf.setStrokeColor(COLOR_BORDER)
        pdf.line(LEFT_MARGIN, BOTTOM_MARGIN - 0.35 * cm, PAGE_WIDTH - RIGHT_MARGIN, BOTTOM_MARGIN - 0.35 * cm)
        pdf.setFont("Helvetica", 8)
        pdf.setFillColor(COLOR_MUTED)
        pdf.drawString(LEFT_MARGIN, BOTTOM_MARGIN - 0.75 * cm, "Generated by Adversarial EDA")
        pdf.drawRightString(PAGE_WIDTH - RIGHT_MARGIN, BOTTOM_MARGIN - 0.75 * cm, f"Page {page_number}")

    def new_page() -> None:
        nonlocal y, page_number
        draw_footer()
        pdf.showPage()
        page_number += 1
        y = PAGE_HEIGHT - TOP_MARGIN

    def ensure_space(required: float) -> None:
        if y - required < BOTTOM_MARGIN:
            new_page()

    def set_font(name: str, size: float, fill=COLOR_INK) -> None:
        pdf.setFont(name, size)
        pdf.setFillColor(fill)

    def wrap_text(text: str, font_name: str, font_size: float, max_width: float) -> list[str]:
        words = sanitize(text).split()
        if not words:
            return [""]

        lines: list[str] = []
        current = ""
        for word in words:
            candidate = word if not current else f"{current} {word}"
            if stringWidth(candidate, font_name, font_size) <= max_width:
                current = candidate
                continue
            if current:
                lines.append(current)
            current = word

        if current:
            lines.append(current)
        return lines

    def text_block(text: str, x: float, width: float, font_name: str = "Helvetica", font_size: float = 10.5, leading: float = 0.48 * cm, fill=COLOR_INK) -> float:
        nonlocal y
        lines = wrap_text(text, font_name, font_size, width)
        height = max(1, len(lines)) * leading
        ensure_space(height)
        set_font(font_name, font_size, fill)
        for line in lines:
            pdf.drawString(x, y, line)
            y -= leading
        return height

    def section_title(title: str) -> None:
        nonlocal y
        ensure_space(1.2 * cm)
        y -= 0.15 * cm
        set_font("Helvetica-Bold", 14, COLOR_ACCENT_DARK)
        pdf.drawString(LEFT_MARGIN, y, title)
        y -= 0.18 * cm
        pdf.setStrokeColor(COLOR_ACCENT)
        pdf.setLineWidth(1.4)
        pdf.line(LEFT_MARGIN, y, LEFT_MARGIN + CONTENT_WIDTH, y)
        y -= 0.45 * cm

    def chip(x: float, top: float, width: float, label: str, value: str) -> None:
        pdf.setFillColor(COLOR_PANEL)
        pdf.setStrokeColor(COLOR_BORDER)
        pdf.roundRect(x, top - 1.45 * cm, width, 1.25 * cm, 5, stroke=1, fill=1)
        set_font("Helvetica", 8.5, COLOR_MUTED)
        pdf.drawString(x + 0.25 * cm, top - 0.5 * cm, label)
        set_font("Helvetica-Bold", 13, COLOR_INK)
        pdf.drawString(x + 0.25 * cm, top - 1.02 * cm, value)

    def draw_overview() -> None:
        nonlocal y
        descriptive = state.data_profile.get("descriptive_statistics", {})
        overview = descriptive.get("overview", {})
        column_types = overview.get("column_types") or {}

        section_title("Dataset Overview")
        ensure_space(3.1 * cm)
        card_width = (CONTENT_WIDTH - 0.45 * cm * 3) / 4
        top = y
        chip(LEFT_MARGIN, top, card_width, "Rows", fmt(overview.get("rows")))
        chip(LEFT_MARGIN + (card_width + 0.45 * cm), top, card_width, "Columns", fmt(overview.get("columns")))
        chip(LEFT_MARGIN + 2 * (card_width + 0.45 * cm), top, card_width, "Missing Cells", fmt(overview.get("missing_cells")))
        chip(LEFT_MARGIN + 3 * (card_width + 0.45 * cm), top, card_width, "Duplicate Rows", fmt(overview.get("duplicate_rows")))
        y -= 1.8 * cm

        missing_percent = overview.get("missing_cells_percent")
        duplicate_percent = overview.get("duplicate_rows_percent")
        text_block(
            f"Missing rate: {fmt_percent(missing_percent)}. Duplicate row rate: {fmt_percent(duplicate_percent)}.",
            LEFT_MARGIN,
            CONTENT_WIDTH,
            fill=COLOR_MUTED,
        )
        if column_types:
            text_block(f"Column mix: {fmt(column_types)}.", LEFT_MARGIN, CONTENT_WIDTH, fill=COLOR_MUTED)
            y -= 0.1 * cm

    def table_header(headers: list[str], widths: list[float]) -> None:
        nonlocal y
        ensure_space(0.7 * cm)
        pdf.setFillColor(COLOR_ACCENT_DARK)
        pdf.roundRect(LEFT_MARGIN, y - 0.55 * cm, CONTENT_WIDTH, 0.55 * cm, 3, stroke=0, fill=1)
        set_font("Helvetica-Bold", 8.5, colors.white)
        x = LEFT_MARGIN + 0.15 * cm
        for header, width in zip(headers, widths):
            pdf.drawString(x, y - 0.36 * cm, header)
            x += width
        y -= 0.65 * cm

    def table_row(values: list[str], widths: list[float], row_index: int) -> None:
        nonlocal y
        row_height = 0.72 * cm
        ensure_space(row_height)
        pdf.setFillColor(COLOR_PANEL if row_index % 2 == 0 else colors.white)
        pdf.rect(LEFT_MARGIN, y - row_height + 0.08 * cm, CONTENT_WIDTH, row_height, stroke=0, fill=1)
        set_font("Helvetica", 8.3, COLOR_INK)
        x = LEFT_MARGIN + 0.15 * cm
        for value, width in zip(values, widths):
            clipped = value
            while clipped and stringWidth(clipped, "Helvetica", 8.3) > width - 0.25 * cm:
                clipped = clipped[:-4].rstrip() + "..."
            pdf.drawString(x, y - 0.38 * cm, clipped)
            x += width
        y -= row_height

    def format_top_values(values: list[dict]) -> str:
        return ", ".join(
            f"{item.get('value')} ({item.get('count')})"
            for item in values
            if isinstance(item, dict)
        )

    def draw_at_a_glance() -> None:
        nonlocal y
        summary = sanitize(state.executive_summary)
        if not summary:
            return
        section_title("At a Glance")
        lines = wrap_text(summary, "Helvetica", 10.5, CONTENT_WIDTH - 0.7 * cm)
        height = max(1.15 * cm, len(lines) * 0.48 * cm + 0.55 * cm)
        ensure_space(height)
        top = y
        pdf.setFillColor(COLOR_PANEL_ALT)
        pdf.setStrokeColor(COLOR_BORDER)
        pdf.roundRect(LEFT_MARGIN, y - height, CONTENT_WIDTH, height, 5, stroke=1, fill=1)
        y = top - 0.38 * cm
        text_block(summary, LEFT_MARGIN + 0.35 * cm, CONTENT_WIDTH - 0.7 * cm, font_size=10.5)
        y = top - height - 0.2 * cm
        y_gap(0.2 * cm)

    def draw_data_quality_notes() -> None:
        notes = [sanitize(note) for note in state.data_quality_notes if sanitize(note)]
        if not notes:
            return
        section_title("Data Quality Notes")
        for note in notes:
            text_block(f"- {note}", LEFT_MARGIN, CONTENT_WIDTH, font_size=10, fill=COLOR_INK)
        y_gap(0.15 * cm)

    def draw_column_summary() -> None:
        descriptive = state.data_profile.get("descriptive_statistics", {})
        columns = descriptive.get("columns", [])
        numeric_columns = [column for column in columns if column.get("type") == "Numeric"]
        categorical_columns = [column for column in columns if column.get("type") != "Numeric"]

        section_title("Column Summary")
        if numeric_columns:
            text_block("Numeric columns", LEFT_MARGIN, CONTENT_WIDTH, "Helvetica-Bold", 10.5, fill=COLOR_SUCCESS)
            widths = [4.2 * cm, 2.4 * cm, 2.4 * cm, 3.2 * cm, 2.2 * cm, 2.2 * cm]
            table_header(["Column", "Mean", "Std Dev", "Range", "Missing", "Distinct"], widths)
            for idx, column in enumerate(numeric_columns):
                table_row(
                    [
                        humanize(column.get("name", "")),
                        fmt(column.get("mean")),
                        fmt(column.get("std")),
                        f"{fmt(column.get('min'))} to {fmt(column.get('max'))}",
                        fmt(column.get("missing")),
                        fmt(column.get("distinct")),
                    ],
                    widths,
                    idx,
                )
            y_gap()

        if categorical_columns:
            text_block("Categorical and boolean columns", LEFT_MARGIN, CONTENT_WIDTH, "Helvetica-Bold", 10.5, fill=COLOR_SUCCESS)
            widths = [4.0 * cm, 2.6 * cm, 2.1 * cm, 2.1 * cm, 6.1 * cm]
            table_header(["Column", "Type", "Missing", "Distinct", "Most Common Values"], widths)
            for idx, column in enumerate(categorical_columns):
                table_row(
                    [
                        humanize(column.get("name", "")),
                        humanize(column.get("type", "")),
                        fmt(column.get("missing")),
                        fmt(column.get("distinct")),
                        format_top_values(column.get("top_values", [])),
                    ],
                    widths,
                    idx,
                )
            y_gap()

    def draw_sample_rows() -> None:
        if state.cleaned_df is None or state.cleaned_df.empty:
            return

        sample = state.cleaned_df.head(MAX_SAMPLE_ROWS)
        columns = [str(column) for column in sample.columns]
        if not columns:
            return

        section_title("Sample Rows")
        text_block(
            f"First {len(sample)} rows after preparation.",
            LEFT_MARGIN,
            CONTENT_WIDTH,
            font_size=9.5,
            fill=COLOR_MUTED,
        )
        for start in range(0, len(columns), MAX_SAMPLE_COLUMNS_PER_TABLE):
            chunk = columns[start:start + MAX_SAMPLE_COLUMNS_PER_TABLE]
            if len(columns) > MAX_SAMPLE_COLUMNS_PER_TABLE:
                text_block(
                    f"Columns {start + 1}-{start + len(chunk)} of {len(columns)}",
                    LEFT_MARGIN,
                    CONTENT_WIDTH,
                    "Helvetica-Bold",
                    9,
                    fill=COLOR_SUCCESS,
                )
            usable_width = CONTENT_WIDTH - 0.3 * cm
            widths = [usable_width / len(chunk)] * len(chunk)
            table_header([humanize(column) for column in chunk], widths)
            for row_index, (_, row) in enumerate(sample.iterrows()):
                table_row([fmt(row[column]) for column in chunk], widths, row_index)
            y_gap(0.2 * cm)

    def y_gap(amount: float = 0.35 * cm) -> None:
        nonlocal y
        y -= amount

    def draw_preparation() -> None:
        plan = state.cleaning_plan
        if not plan:
            return
        if not plan.fill_missing and not plan.remove_outliers and not plan.type_conversions:
            return

        section_title("Data Preparation")
        items = [
            ("Missing values filled", "Yes" if plan.fill_missing else "No"),
            ("Outlier handling", "Enabled" if plan.remove_outliers else "Not applied"),
            ("Outlier columns", ", ".join(humanize(col) for col in plan.outlier_columns) if plan.outlier_columns else "None"),
            (
                "Type conversions",
                ", ".join(f"{humanize(item.column)} to {item.target_dtype}" for item in plan.type_conversions) if plan.type_conversions else "None",
            ),
        ]
        for label, value in items:
            text_block(f"{label}: {value}", LEFT_MARGIN, CONTENT_WIDTH, font_size=10, fill=COLOR_INK)
        y_gap()

    def draw_findings() -> None:
        nonlocal y
        section_title("Key Findings")
        accepted = [insight for insight in state.insight_ledger if insight.skeptic.verdict.value == "ACCEPT"]
        if not accepted:
            text_block("No accepted findings were generated.", LEFT_MARGIN, CONTENT_WIDTH, fill=COLOR_MUTED)
            return

        for idx, insight in enumerate(accepted, start=1):
            narrative = sanitize(insight.narrative)
            lines = wrap_text(narrative, "Helvetica", 10.5, CONTENT_WIDTH - 1.35 * cm)
            height = max(1.25 * cm, 0.45 * cm * len(lines) + 0.55 * cm)
            ensure_space(height + 0.25 * cm)
            pdf.setFillColor(COLOR_PANEL_ALT)
            pdf.setStrokeColor(COLOR_BORDER)
            pdf.roundRect(LEFT_MARGIN, y - height, CONTENT_WIDTH, height, 5, stroke=1, fill=1)
            pdf.setFillColor(COLOR_ACCENT)
            pdf.circle(LEFT_MARGIN + 0.45 * cm, y - 0.52 * cm, 0.18 * cm, stroke=0, fill=1)
            set_font("Helvetica-Bold", 8.5, colors.white)
            pdf.drawCentredString(LEFT_MARGIN + 0.45 * cm, y - 0.62 * cm, str(idx))
            set_font("Helvetica", 10.5, COLOR_INK)
            line_y = y - 0.42 * cm
            for line in lines:
                pdf.drawString(LEFT_MARGIN + 0.85 * cm, line_y, line)
                line_y -= 0.45 * cm
            y -= height + 0.25 * cm

    def draw_recommended_actions() -> None:
        actions = [sanitize(action) for action in state.recommended_actions if sanitize(action)]
        if not actions:
            return
        section_title("Recommended Next Actions")
        for action in actions:
            text_block(f"- {action}", LEFT_MARGIN, CONTENT_WIDTH, font_size=10.2, fill=COLOR_INK)
        y_gap(0.2 * cm)

    def draw_technical_audit() -> None:
        section_title("Technical Audit")
        for idx, insight in enumerate(state.insight_ledger, start=1):
            text_block(f"{idx}. {humanize(insight.skeptic.verdict.value)}: {sanitize(insight.hypothesis)}", LEFT_MARGIN, CONTENT_WIDTH, "Helvetica-Bold", 9.5)
            text_block(f"Function: {humanize(insight.function_name)}", LEFT_MARGIN + 0.25 * cm, CONTENT_WIDTH - 0.25 * cm, font_size=9, fill=COLOR_MUTED)
            stats = ", ".join(
                f"{humanize(key)}={fmt(value)}"
                for key, value in insight.result.statistics.items()
                if key
                in {
                    "statistic",
                    "p_value",
                    "n",
                    "r_squared",
                    "cohen_d",
                    "cramers_v",
                    "eta_squared",
                    "epsilon_squared",
                    "rank_biserial",
                    "odds_ratio",
                }
            )
            if stats:
                text_block(f"Stats: {stats}", LEFT_MARGIN + 0.25 * cm, CONTENT_WIDTH - 0.25 * cm, font_size=9, fill=COLOR_MUTED)
            text_block(f"Skeptic: {sanitize(insight.skeptic.reason)}", LEFT_MARGIN + 0.25 * cm, CONTENT_WIDTH - 0.25 * cm, font_size=9, fill=COLOR_MUTED)
            y_gap(0.15 * cm)

    set_font("Helvetica-Bold", 22, COLOR_ACCENT_DARK)
    pdf.drawString(LEFT_MARGIN, y, "Statistical EDA Report")
    y -= 0.62 * cm
    set_font("Helvetica", 10.5, COLOR_MUTED)
    pdf.drawString(LEFT_MARGIN, y, f"Dataset: {sanitize(state.dataset_name)}")
    y -= 0.7 * cm

    draw_at_a_glance()
    draw_overview()
    draw_data_quality_notes()
    draw_preparation()
    draw_column_summary()
    draw_sample_rows()
    draw_findings()
    draw_recommended_actions()
    if state.show_execution_order:
        y_gap(0.45 * cm)
        draw_technical_audit()

    draw_footer()
    pdf.save()
    buffer.seek(0)
    return buffer.read()
